// 4 Productos del sistema
export const mockProducts = [
  { id: '1', name: 'Fleet Management', description: 'Sistema de gestión de flotas' },
  { id: '2', name: 'E&D', description: 'Energía y Dinámica' },
  { id: '3', name: 'Wayside', description: 'Monitoreo de vía' },
  { id: '4', name: 'Advanced Analytics', description: 'Análisis avanzado y reportes' },
];

// Cliente Actren
export const mockClient = {
  id: 'client-actren',
  name: 'Actren',
  userLimit: 20,
  currentUserCount: 20,
  projects: [],
  contactEmail: 'soporte@caf.com',
  contactPhone: '+34 943 123 456',
  createdAt: new Date('2023-01-15'),
};

// Flotas de Actren (3 flotas)
export const mockFleets = [
  { id: 'fleet-1', name: 'Flota 1', projectId: 'proj-actren' },
  { id: 'fleet-2', name: 'Flota 2', projectId: 'proj-actren' },
  { id: 'fleet-3', name: 'Flota 3', projectId: 'proj-actren' },
];

// Proyecto Actren
export const mockProject = {
  id: 'proj-actren',
  name: 'Actren',
  clientId: 'client-actren',
  fleets: mockFleets,
  contractedProducts: ['1', '2', '3', '4'],
  createdAt: new Date('2023-01-15'),
};

mockClient.projects = [mockProject];

// Roles del sistema y personalizados
export const mockCustomRoles = [
  // Fleet Management - Roles del sistema
  {
    id: 'fm-basico',
    name: 'Básico',
    description: 'Acceso básico a Fleet Management',
    productId: '1',
    permissions: {
      alarmasNivel1y2: true,
      todasLasAlarmas: false,
      compartirEventosNotificaciones: true,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
  {
    id: 'fm-avanzado',
    name: 'Avanzado',
    description: 'Acceso avanzado a Fleet Management',
    productId: '1',
    permissions: {
      alarmasNivel1y2: true,
      todasLasAlarmas: true,
      compartirEventosNotificaciones: true,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
  // E&D - Roles del sistema
  {
    id: 'ed-basico',
    name: 'Básico',
    description: 'Acceso básico a E&D',
    productId: '2',
    permissions: {
      verDatos: true,
      exportarDatos: false,
      configurarParametros: false,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
  {
    id: 'ed-avanzado',
    name: 'Avanzado',
    description: 'Acceso avanzado a E&D',
    productId: '2',
    permissions: {
      verDatos: true,
      exportarDatos: true,
      configurarParametros: true,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
  // Wayside - Roles del sistema
  {
    id: 'ws-basico',
    name: 'Básico',
    description: 'Acceso básico a Wayside',
    productId: '3',
    permissions: {
      verMediciones: true,
      crearMediciones: false,
      exportarReportes: false,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
  {
    id: 'ws-avanzado',
    name: 'Avanzado',
    description: 'Acceso avanzado a Wayside',
    productId: '3',
    permissions: {
      verMediciones: true,
      crearMediciones: true,
      exportarReportes: true,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
  // Advanced Analytics - Roles del sistema
  {
    id: 'aa-basico',
    name: 'Básico',
    description: 'Acceso básico a Advanced Analytics',
    productId: '4',
    permissions: {
      verDashboards: true,
      crearDashboards: false,
      exportarReportes: false,
      configurarAlertas: false,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
  {
    id: 'aa-avanzado',
    name: 'Avanzado',
    description: 'Acceso avanzado a Advanced Analytics',
    productId: '4',
    permissions: {
      verDashboards: true,
      crearDashboards: true,
      exportarReportes: true,
      configurarAlertas: true,
    },
    createdAt: new Date('2023-01-15'),
    createdBy: 'system',
    isSystem: false,
  },
];

// Usuarios mock (20 usuarios totales)
export const mockUsers = [
  // Pool Cliente (10 usuarios)
  {
    id: 'user-1',
    email: 'juan.perez@actren.com',
    name: 'Juan Pérez',
    username: 'jperez',
    profile: 'Jefe',
    grupo: 'Gestión',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: ['fleet-1', 'fleet-2'] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2024-10-01'),
    createdBy: 'system',
    lastAccess: new Date('2025-10-14T10:30:00'),
  },
  {
    id: 'user-2',
    email: 'ana.garcia@actren.com',
    name: 'Ana García',
    username: 'agarcia',
    profile: 'Analista',
    grupo: 'Operaciones',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: ['fleet-1'] },
      { productId: '2', roleId: null, fleetIds: [] },
      { productId: '3', roleId: 'ws-basico', fleetIds: [] },
      { productId: '4', roleId: null, fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2024-09-20'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-13T14:15:00'),
  },
  {
    id: 'user-3',
    email: 'carlos.lopez@actren.com',
    name: 'Carlos López',
    username: 'clopez',
    profile: 'Técnico',
    grupo: 'Mantenimiento',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: ['fleet-2'] },
      { productId: '2', roleId: 'ed-basico', fleetIds: [] },
      { productId: '3', roleId: null, fleetIds: [] },
      { productId: '4', roleId: null, fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-04-22'),
    updatedAt: new Date('2024-08-30'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-12T09:45:00'),
  },
  {
    id: 'user-4',
    email: 'maria.rodriguez@actren.com',
    name: 'María Rodríguez',
    username: 'mrodriguez',
    profile: 'Jefe',
    grupo: 'Supervisión',
    status: 'bloqueado',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: { reason: 'Bloqueado Ciberseguridad - Intento de acceso no autorizado' },
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date('2024-09-01'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-08-30T16:20:00'),
  },
  {
    id: 'user-5',
    email: 'luis.martinez@actren.com',
    name: 'Luis Martínez',
    username: 'lmartinez',
    profile: 'Analista',
    grupo: 'Análisis',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'es',
    numberFormat: 'dot',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: ['fleet-1'] },
      { productId: '2', roleId: 'ed-basico', fleetIds: [] },
      { productId: '3', roleId: 'ws-basico', fleetIds: [] },
      { productId: '4', roleId: 'aa-basico', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2024-07-15'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-10T11:20:00'),
  },
  {
    id: 'user-6',
    email: 'sofia.fernandez@actren.com',
    name: 'Sofía Fernández',
    username: 'sfernandez',
    profile: 'Técnico',
    grupo: 'Operaciones',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'en',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: ['fleet-2', 'fleet-3'] },
      { productId: '2', roleId: null, fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: null, fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-07-05'),
    updatedAt: new Date('2024-06-10'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-11T15:30:00'),
  },
  {
    id: 'user-7',
    email: 'pedro.sanchez@actren.com',
    name: 'Pedro Sánchez',
    username: 'psanchez',
    profile: 'Analista',
    grupo: 'Gestión',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'de',
    numberFormat: 'dot',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: null, fleetIds: [] },
      { productId: '4', roleId: 'aa-basico', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-08-12'),
    updatedAt: new Date('2024-05-20'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-09T08:45:00'),
  },
  {
    id: 'user-8',
    email: 'laura.gomez@actren.com',
    name: 'Laura Gómez',
    username: 'lgomez',
    profile: 'Jefe',
    grupo: 'Supervisión',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: ['fleet-1', 'fleet-3'] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-09-18'),
    updatedAt: new Date('2024-04-25'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-14T16:00:00'),
  },
  {
    id: 'user-9',
    email: 'javier.ruiz@actren.com',
    name: 'Javier Ruiz',
    username: 'jruiz',
    profile: 'Técnico',
    grupo: 'Mantenimiento',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'es',
    numberFormat: 'dot',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: ['fleet-3'] },
      { productId: '2', roleId: null, fleetIds: [] },
      { productId: '3', roleId: 'ws-basico', fleetIds: [] },
      { productId: '4', roleId: null, fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-10-22'),
    updatedAt: new Date('2024-03-30'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-08T12:10:00'),
  },
  {
    id: 'user-10',
    email: 'isabel.moreno@actren.com',
    name: 'Isabel Moreno',
    username: 'imoreno',
    profile: 'Analista',
    grupo: 'Análisis',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool Cliente',
    language: 'en',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: ['fleet-2'] },
      { productId: '2', roleId: 'ed-basico', fleetIds: [] },
      { productId: '3', roleId: null, fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2024-02-18'),
    createdBy: 'user-1',
    lastAccess: new Date('2025-10-13T09:25:00'),
  },

  // Pool CAF (10 usuarios)
  {
    id: 'user-caf-1',
    email: 'caf.admin@cafdigitalservices.com',
    name: 'CAF Admin',
    username: 'cafadmin',
    profile: 'Jefe',
    grupo: 'Administración CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date('2024-10-05'),
    createdBy: 'system',
    lastAccess: new Date('2025-10-14T14:45:00'),
  },
  {
    id: 'user-caf-2',
    email: 'caf.soporte1@cafdigitalservices.com',
    name: 'CAF Soporte 1',
    username: 'cafsoporte1',
    profile: 'Técnico',
    grupo: 'Soporte CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-basico', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-basico', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2024-09-10'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-13T11:30:00'),
  },
  {
    id: 'user-caf-3',
    email: 'caf.soporte2@cafdigitalservices.com',
    name: 'CAF Soporte 2',
    username: 'cafsoporte2',
    profile: 'Técnico',
    grupo: 'Soporte CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'en',
    numberFormat: 'dot',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-basico', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2024-08-20'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-12T15:20:00'),
  },
  {
    id: 'user-caf-4',
    email: 'caf.analista1@cafdigitalservices.com',
    name: 'CAF Analista 1',
    username: 'cafanalista1',
    profile: 'Analista',
    grupo: 'Análisis CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'de',
    numberFormat: 'dot',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2024-07-25'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-11T10:15:00'),
  },
  {
    id: 'user-caf-5',
    email: 'caf.supervisor@cafdigitalservices.com',
    name: 'CAF Supervisor',
    username: 'cafsupervisor',
    profile: 'Jefe',
    grupo: 'Supervisión CAF',
    status: 'bloqueado',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: { reason: 'Bloqueado Ciberseguridad - Acceso suspendido temporalmente' },
    createdAt: new Date('2023-05-12'),
    updatedAt: new Date('2024-06-30'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-09-15T13:40:00'),
  },
  {
    id: 'user-caf-6',
    email: 'caf.tecnico1@cafdigitalservices.com',
    name: 'CAF Técnico 1',
    username: 'caftecnico1',
    profile: 'Técnico',
    grupo: 'Mantenimiento CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'es',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: [] },
      { productId: '2', roleId: 'ed-basico', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-basico', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2024-05-15'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-10T14:50:00'),
  },
  {
    id: 'user-caf-7',
    email: 'caf.analista2@cafdigitalservices.com',
    name: 'CAF Analista 2',
    username: 'cafanalista2',
    profile: 'Analista',
    grupo: 'Análisis CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'en',
    numberFormat: 'dot',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-basico', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-07-18'),
    updatedAt: new Date('2024-04-10'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-09T16:25:00'),
  },
  {
    id: 'user-caf-8',
    email: 'caf.tecnico2@cafdigitalservices.com',
    name: 'CAF Técnico 2',
    username: 'caftecnico2',
    profile: 'Técnico',
    grupo: 'Soporte CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'de',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-basico', fleetIds: [] },
      { productId: '2', roleId: 'ed-basico', fleetIds: [] },
      { productId: '3', roleId: 'ws-basico', fleetIds: [] },
      { productId: '4', roleId: 'aa-basico', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-08-25'),
    updatedAt: new Date('2024-03-20'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-08T09:35:00'),
  },
  {
    id: 'user-caf-9',
    email: 'caf.coordinador@cafdigitalservices.com',
    name: 'CAF Coordinador',
    username: 'cafcoordinador',
    profile: 'Jefe',
    grupo: 'Coordinación CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'es',
    numberFormat: 'dot',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-avanzado', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-09-30'),
    updatedAt: new Date('2024-02-28'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-14T11:55:00'),
  },
  {
    id: 'user-caf-10',
    email: 'caf.especialista@cafdigitalservices.com',
    name: 'CAF Especialista',
    username: 'cafespecialista',
    profile: 'Analista',
    grupo: 'Especialistas CAF',
    status: 'activo',
    clientId: 'client-actren',
    projectId: 'proj-actren',
    poolClient: 'Pool CAF',
    language: 'en',
    numberFormat: 'comma',
    productPermissions: [
      { productId: '1', roleId: 'fm-avanzado', fleetIds: [] },
      { productId: '2', roleId: 'ed-avanzado', fleetIds: [] },
      { productId: '3', roleId: 'ws-avanzado', fleetIds: [] },
      { productId: '4', roleId: 'aa-basico', fleetIds: [] },
    ],
    metadata: {},
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-01-25'),
    createdBy: 'user-caf-1',
    lastAccess: new Date('2025-10-13T13:10:00'),
  },
];

// Mock de auditoría
export const mockAuditLog = [
  {
    id: 'audit1',
    userId: 'user-1',
    action: 'Permisos modificados',
    performedBy: 'user-1',
    timestamp: new Date('2024-10-01T10:30:00'),
    before: { productPermissions: [{ productId: '1', roleId: 'fm-basico' }] },
    after: { productPermissions: [{ productId: '1', roleId: 'fm-avanzado' }] },
    reason: 'Promoción a rol avanzado',
    details: 'Cambio de rol en Fleet Management',
  },
  {
    id: 'audit2',
    userId: 'user2',
    action: 'Usuario bloqueado',
    performedBy: 'user-1',
    timestamp: new Date('2024-09-15T14:20:00'),
    before: { status: 'activo' },
    after: { status: 'bloqueado' },
    reason: 'Bloqueado Ciberseguridad',
    details: 'Usuario bloqueado por políticas de seguridad',
  },
  {
    id: 'audit3',
    userId: 'user3',
    action: 'Permisos modificados',
    performedBy: 'user-1',
    timestamp: new Date('2024-08-22T09:15:00'),
    before: { productPermissions: [{ productId: '2', roleId: null }] },
    after: { productPermissions: [{ productId: '2', roleId: 'ed-basico' }] },
    reason: 'Asignación de producto E&D',
    details: 'Usuario añadido al producto E&D',
  },
];

// Mock Assets
export const mockAssets = [
  // Activos de Fleet Management - user-1
  { id: 'asset-1', type: 'notificacion', name: 'Alerta de Velocidad', ownerId: 'user-1', projectId: 'proj-actren', productId: '1', fleetId: 'fleet-1', canBeReassigned: true },
  { id: 'asset-2', type: 'notificacion', name: 'Notificación Mantenimiento', ownerId: 'user-1', projectId: 'proj-actren', productId: '1', fleetId: 'fleet-1', canBeReassigned: true },
  { id: 'asset-3', type: 'telemetria', name: 'Plantilla Telemetría Básica', ownerId: 'user-1', projectId: 'proj-actren', productId: '1', canBeReassigned: true },
  { id: 'asset-4', type: 'telemetria', name: 'Plantilla Telemetría Avanzada', ownerId: 'user-1', projectId: 'proj-actren', productId: '1', canBeReassigned: true },
  { id: 'asset-5', type: 'evento', name: 'Evento Mantenimiento Programado', ownerId: 'user-1', projectId: 'proj-actren', productId: '1', fleetId: 'fleet-2', canBeReassigned: true },
  { id: 'asset-6', type: 'evento', name: 'Evento Revisión Técnica', ownerId: 'user-1', projectId: 'proj-actren', productId: '1', fleetId: 'fleet-1', canBeReassigned: true },
  { id: 'asset-7', type: 'evento', name: 'Evento Inspección', ownerId: 'user-1', projectId: 'proj-actren', productId: '1', fleetId: 'fleet-3', canBeReassigned: true },

  // Activos de E&D - user-1
  { id: 'asset-8', type: 'plantilla', name: 'Plantilla ED Consumo Energético', ownerId: 'user-1', projectId: 'proj-actren', productId: '2', canBeReassigned: true },
  { id: 'asset-9', type: 'plantilla', name: 'Plantilla ED Dinámica', ownerId: 'user-1', projectId: 'proj-actren', productId: '2', canBeReassigned: true },

  // Activos de Wayside - user-1
  { id: 'asset-10', type: 'medicion_wayside', name: 'Medición Vía Principal', ownerId: 'user-1', projectId: 'proj-actren', productId: '3', canBeReassigned: true },
  { id: 'asset-11', type: 'medicion_wayside', name: 'Medición Vía Secundaria', ownerId: 'user-1', projectId: 'proj-actren', productId: '3', canBeReassigned: true },
  { id: 'asset-12', type: 'medicion_wayside', name: 'Medición Estación Central', ownerId: 'user-1', projectId: 'proj-actren', productId: '3', canBeReassigned: true },

  // Activos adicionales de otros usuarios
  { id: 'asset-13', type: 'notificacion', name: 'Alerta Temperatura Motor', ownerId: 'user2', projectId: 'proj-actren', productId: '1', fleetId: 'fleet-1', canBeReassigned: true },
  { id: 'asset-14', type: 'telemetria', name: 'Dashboard Flota 2 Completo', ownerId: 'user3', projectId: 'proj-actren', productId: '1', fleetId: 'fleet-2', canBeReassigned: true },
  { id: 'asset-15', type: 'evento', name: 'Evento Mantenimiento Preventivo', ownerId: 'user4', projectId: 'proj-actren', productId: '1', canBeReassigned: true },
  { id: 'asset-16', type: 'medicion_wayside', name: 'Medición Bogie Secundario', ownerId: 'user2', projectId: 'proj-actren', productId: '3', fleetId: 'fleet-1', canBeReassigned: true },
  { id: 'asset-17', type: 'plantilla', name: 'Plantilla Análisis Dinámico Básico', ownerId: 'user5', projectId: 'proj-actren', productId: '2', canBeReassigned: true },
];

// Helper: Calculate user limit warning
export const getUserLimitWarning = () => {
  const activeUsers = mockUsers.filter(u => u.status === 'activo').length;
  const limit = mockClient.userLimit;
  const remaining = limit - activeUsers;
  const percentage = (activeUsers / limit) * 100;

  return {
    current: activeUsers,
    limit: limit,
    isAtLimit: activeUsers >= limit,
    isNearLimit: percentage >= 90,
    remainingSlots: remaining,
  };
};

// Helper functions
export const getUserAssets = (userId) => {
  return mockAssets.filter(a => a.ownerId === userId);
};

export const hasBlockingAssets = (userId) => {
  const assets = getUserAssets(userId);
  return assets.some(a => a.type === 'medicion_wayside');
};

export const getProductName = (productId) => {
  return mockProducts.find(p => p.id === productId)?.name || 'Desconocido';
};

export const getFleetName = (fleetId) => {
  return mockFleets.find(f => f.id === fleetId)?.name || 'Desconocido';
};

// Usuario actual del sistema
export let currentUser = mockUsers[0]; // Admin
